name: at_spi
version: 0.0.1

description:
  Provides access to the Assistive Technology Service Provider Interface (AT-SPI), the standard for accessibility on Linux desktops.

homepage: https://github.com/canonical/at_spi.dart

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dbus: ^0.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8
  test_cov: ^1.0.1
